### PR TITLE
Add GH build workflow

### PR DESCRIPTION
**Pull request by aalmiray**

### CODE REVIEW

**Comment by nemecec** [comment]
Thanks for the pull request! As it did not cover my original requirements (for example, Java 6 is missing), I used this PR as inspiration and created my own: https://github.com/zeroturnaround/zt-exec/pull/109

**Comment by aalmiray** [comment]
Java6 was not used because the build requires Java7 as a minimum. I'd recommend raising the baseline to Java7.

**Comment by nemecec** [comment]
What do you mean by "the build requires"?

**Comment by aalmiray** [comment]
The ModiTect plugin must be run with Java 9 or greater.

**Comment by nemecec** [comment]
Yes, Maven (including the plugin) is run with newer Java. But generated bytecode is compatible with Java 6.

**Pull request closed without merging**
