### PR TITLE
Added capture of prior IOExceptions as suppressed instead of ignored.

### PR DESCRIPTION
**Pull request by footloosejava**

### CODE REVIEW

**Comment by reinra** [comment]
Could you also add unit tests for this line ProcessOutput.getLinesFrom() to capture 3 different line endings (\n, \r and \r\n)?

It's nice to hear about the processing stopping.

**Comment by footloosejava** [comment]
I send in the Pull request with Reflection for addSuppressed.

**Comment by footloosejava** [comment]
Re: Could you also add unit tests for this line ProcessOutput.getLinesFrom() to capture 3 different line endings (\n, \r and \r\n)?

I never use \r alone as a newline ... But I see that Java's BufferedReader does. So I think you have it right - already :)

**Comment by reinra** [comment]
I added the [unit test for line endings](https://github.com/zeroturnaround/zt-exec/commit/d0b03d07f189d583ae8e7a0caedd579433d5df44) which passes.
I also added the [suppressed exception handling](https://github.com/zeroturnaround/zt-exec/commit/0f5390b4630c8dc8acdd3be385fd5a90232e5a3b) with some modifications.
I changed the exception handling order so that now we'll actually throw the first exception instead of the last one. This seems better as there's a better chance of seeing the root cause.

**Pull request closed without merging**
